### ISSUE TITLE
Can I use Notepad Notebook Extension for Question Forms?

### ISSUE THREAD

**Issue by GeorgBraun** [Devon7925/vscode-notepad#1]
Thanks a lot for providing the Notepad Notebook Extension!

I am currently evaluating, if I could use it for some "simple question-forms" for my students with storing the answers in markdown-files on the local file system (web-access is deactivated for my students).

The following image is an example for what I have achieved so far using your extension:
![grafik](https://user-images.githubusercontent.com/17134433/152845911-4c75a6a8-25a5-4c17-8028-8035997b5559.png)

The file contents are straight forward:

````markdown
# Questions

### 1. RISC and CISC

Describe the differences between **RISC** and **CISC**:

```txt

```

---

### 2. Von Neumann architecture

![test](./img/von-neumann-01.png)

Fill in the names of the individual components according to above picture:

```txt
1. 
2. 
3. 
4. 
5. 
6. 
```

````

As you can see, I am using regular markdown to describe the questions including some images if needed and code blocks as kind of a free text form field where students put their answers into.

In order to make the questions as much "read only" as I could, I am using the following VSCode workspace settings:

```json
  "notebook.diff.enablePreview": false,
  "notebook.globalToolbar": false,
  "notebook.globalToolbarShowLabel": "never",
  "notebook.insertToolbarLocation": "hidden",
  "notebook.markup.fontSize": 14,
  "notebook.showCellStatusBar": "hidden",
  "notebook.dragAndDropEnabled": false,
  "notebook.consolidatedOutputButton": false,
  "notebook.cellFocusIndicator": "gutter",
  "notebook.cellToolbarVisibility":"click",
  "notebook.compactView":true,
  "notebook.showFoldingControls":"mouseover",
  "notebook.breadcrumbs.showCodeCells": false,
  "notebook.cellToolbarLocation": {
    "default":"hidden"
  },
  "notebook.navigation.allowNavigateToSurroundingCells":false,
```

This seems to work pretty well so far: If I click into a code block, I can enter my answer which is the stored by the auto save feature of VSCode.

So far, so good 😄 

One problem, that I am currently struggling with, is the behaviour in case of a double click: 

If I double click on the area outside of a code block, I can enter the edit mode of the surrounding notebook cells, e.g.

![grafik](https://user-images.githubusercontent.com/17134433/152847647-dc8e3ffd-00e5-453f-add8-cccd86651b3a.png)

This would allow anybody to modify my questions to something they prefer ...

So I think, at the moment, I would have two questions:

1. I guess I am using your extension beyond your original scope. Am I moving away too far?
2. Would it be possible to block the double click event? I have searched the VSCode settings but could not find anything so far.

Many thanks and best regards,<br>
&nbsp;Georg

**Comment by Devon7925** [comment]
For 1, I definitely see how an extension like this could be useful for your use case. However, I don't know of any way to block the double click as that is a default vs code thing. In addition, there is the `View: Reopen Editor With Text Editor` Command that would allow your students to edit the files even if you could block the double click.

**Comment by GeorgBraun** [comment]
Thank you very much for your timely and helpful response.

I agree with you - it simply seems to much work to strip down such a perfect editor like VSCode into something with very limited functionality during an exam.

Thinking about my requirements, it seems that using something like Electron as a secured browser view might be a better fit. I guess, I will look into this as my next step.

Many thanks and best regards,
&nbsp;Georg
